import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const pixelify_sans = Pixelify_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Sliding Puzzle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={pixelify_sans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
